language: node_js
node_js:
- "stable"
install: "npm install --no-optional"
script: "./deploy-ghpages.sh"
cache:
  directories:
  - node_modules
env:
  global:
  - GH_REF: github.com/justgook/sokoban-react.git
  - secure: KjcCDscK81c/HziGfiy8jb4BYnsuxYPH5DEcZnNz5B6EOAhCt7Q6UCOt6jcO6YdDcgHEZ+p8TAjtr6GIo/ymZe957o+EfqmdoDchvbNPfhEmACpNXaa5gcNDj2RrF8+mnXKqht373qntF/gCefXgs6o+YsjcQ8QzSW9nCZuX0QvYUwFqEHz1o/lXE13zyxWgeAlcmcG73MMtCxMwu34XqJYTt1SYgUvpvrfVKeIdSKMp9LUfqXBCUbObhdwpmZ5UttihzjD8XNR/rIfelGR7zc+u7j071JGzlCg4KwGo7EG1js4W2GxvJmACyfbxiZomKH47u14ismrntf7s2P0NAs08NUOVk2hzBqMjKehQwEuNZFfzXTgPejuP3vHVXaApC+CT87egtCD18RM0pPfYqqP8vQlWNsPsaZwAMMfcN8vM7GhQPr38SnoZDL9FVqtKaJ9AInGt/7Xn0OQwa89PeCc1ZDYEL4vhGnlUDXfes6id/JCNA3OgUjQYepW2GRnO43+jLi5XoHd/bvnVV+XybZW8Aj8XivVNf0gP6SkelD8iPhFhVhmo8U0W6SOKKRRQ6f/DUl8QLvDFlXTwYFq9ctZ+HNg+x8DvSaGKhIQyFLuvQqb7lauO58N31kKoIukY1UPD30W460mVx24s/flSTm/kLyMiWpdE4iyYFbbJjTQ=
